/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth_ResendOTP from "../auth/ResendOTP.js";
import type * as auth_VerificationCodeEmail from "../auth/VerificationCodeEmail.js";
import type * as auth from "../auth.js";
import type * as functions from "../functions.js";
import type * as http from "../http.js";
import type * as init from "../init.js";
import type * as invites from "../invites.js";
import type * as permissions from "../permissions.js";
import type * as types from "../types.js";
import type * as users_teams_members_invites from "../users/teams/members/invites.js";
import type * as users_teams_members from "../users/teams/members.js";
import type * as users_teams_messages from "../users/teams/messages.js";
import type * as users_teams_roles from "../users/teams/roles.js";
import type * as users_teams from "../users/teams.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "auth/ResendOTP": typeof auth_ResendOTP;
  "auth/VerificationCodeEmail": typeof auth_VerificationCodeEmail;
  auth: typeof auth;
  functions: typeof functions;
  http: typeof http;
  init: typeof init;
  invites: typeof invites;
  permissions: typeof permissions;
  types: typeof types;
  "users/teams/members/invites": typeof users_teams_members_invites;
  "users/teams/members": typeof users_teams_members;
  "users/teams/messages": typeof users_teams_messages;
  "users/teams/roles": typeof users_teams_roles;
  "users/teams": typeof users_teams;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
